version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Rust
          command: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - run:
          name: Install WASM Pack
          command: "source $HOME/.cargo/env && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache3-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache3-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Bootstrap
          command: npm run bootstrap
      - run:
          name: Build
          command: "source $HOME/.cargo/env && npm run build"
      - run:
          name: Test
          command: nsource $HOME/.cargo/env && pm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
