name: Checks
on:
  push:
    branches:
      - dev
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: yarn bootstrap
      - run: yarn build
      - uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: yarn bootstrap
      - run: yarn build
      - uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
      - run: yarn coverage:upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn bootstrap
      - run: yarn lint
