name: publish
on: push
jobs:
  publish-packages:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: npm install
      - run: npm run lint
      - run: npm run publish:packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
