name: Test
on:
  push:
    branches:
      - "*"
jobs:
  test-packages:
    name: Test packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: npm install
      - run: npm run build
      - uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - run: npm run coverage:upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint-packages:
    name: Lint packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - run: npm install
      - run: npm run build
      - run: npm run lint
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
